// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.completeBatchStmt, err = db.PrepareContext(ctx, CompleteBatch); err != nil {
		return nil, fmt.Errorf("error preparing query CompleteBatch: %w", err)
	}
	if q.completeProcessStmt, err = db.PrepareContext(ctx, CompleteProcess); err != nil {
		return nil, fmt.Errorf("error preparing query CompleteProcess: %w", err)
	}
	if q.countDomainsStmt, err = db.PrepareContext(ctx, CountDomains); err != nil {
		return nil, fmt.Errorf("error preparing query CountDomains: %w", err)
	}
	if q.countFindingsStmt, err = db.PrepareContext(ctx, CountFindings); err != nil {
		return nil, fmt.Errorf("error preparing query CountFindings: %w", err)
	}
	if q.countURLsStmt, err = db.PrepareContext(ctx, CountURLs); err != nil {
		return nil, fmt.Errorf("error preparing query CountURLs: %w", err)
	}
	if q.deleteNoteStmt, err = db.PrepareContext(ctx, DeleteNote); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteNote: %w", err)
	}
	if q.deleteScopeRuleByPatternStmt, err = db.PrepareContext(ctx, DeleteScopeRuleByPattern); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteScopeRuleByPattern: %w", err)
	}
	if q.getBatchByIDStmt, err = db.PrepareContext(ctx, GetBatchByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetBatchByID: %w", err)
	}
	if q.getDNSRecordsByDomainStmt, err = db.PrepareContext(ctx, GetDNSRecordsByDomain); err != nil {
		return nil, fmt.Errorf("error preparing query GetDNSRecordsByDomain: %w", err)
	}
	if q.getDomainByNameStmt, err = db.PrepareContext(ctx, GetDomainByName); err != nil {
		return nil, fmt.Errorf("error preparing query GetDomainByName: %w", err)
	}
	if q.getDomainsStmt, err = db.PrepareContext(ctx, GetDomains); err != nil {
		return nil, fmt.Errorf("error preparing query GetDomains: %w", err)
	}
	if q.getDownloadedFilesByURLStmt, err = db.PrepareContext(ctx, GetDownloadedFilesByURL); err != nil {
		return nil, fmt.Errorf("error preparing query GetDownloadedFilesByURL: %w", err)
	}
	if q.getFindingsStmt, err = db.PrepareContext(ctx, GetFindings); err != nil {
		return nil, fmt.Errorf("error preparing query GetFindings: %w", err)
	}
	if q.getIPByAddressStmt, err = db.PrepareContext(ctx, GetIPByAddress); err != nil {
		return nil, fmt.Errorf("error preparing query GetIPByAddress: %w", err)
	}
	if q.getLiveDomainsStmt, err = db.PrepareContext(ctx, GetLiveDomains); err != nil {
		return nil, fmt.Errorf("error preparing query GetLiveDomains: %w", err)
	}
	if q.getNotesStmt, err = db.PrepareContext(ctx, GetNotes); err != nil {
		return nil, fmt.Errorf("error preparing query GetNotes: %w", err)
	}
	if q.getPendingItemsStmt, err = db.PrepareContext(ctx, GetPendingItems); err != nil {
		return nil, fmt.Errorf("error preparing query GetPendingItems: %w", err)
	}
	if q.getPortsByIPStmt, err = db.PrepareContext(ctx, GetPortsByIP); err != nil {
		return nil, fmt.Errorf("error preparing query GetPortsByIP: %w", err)
	}
	if q.getProcessByIDStmt, err = db.PrepareContext(ctx, GetProcessByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetProcessByID: %w", err)
	}
	if q.getRunningProcessPIDsStmt, err = db.PrepareContext(ctx, GetRunningProcessPIDs); err != nil {
		return nil, fmt.Errorf("error preparing query GetRunningProcessPIDs: %w", err)
	}
	if q.getScopeRulesStmt, err = db.PrepareContext(ctx, GetScopeRules); err != nil {
		return nil, fmt.Errorf("error preparing query GetScopeRules: %w", err)
	}
	if q.getTechStackByDomainStmt, err = db.PrepareContext(ctx, GetTechStackByDomain); err != nil {
		return nil, fmt.Errorf("error preparing query GetTechStackByDomain: %w", err)
	}
	if q.getURLByFullURLStmt, err = db.PrepareContext(ctx, GetURLByFullURL); err != nil {
		return nil, fmt.Errorf("error preparing query GetURLByFullURL: %w", err)
	}
	if q.getURLFlagsByURLStmt, err = db.PrepareContext(ctx, GetURLFlagsByURL); err != nil {
		return nil, fmt.Errorf("error preparing query GetURLFlagsByURL: %w", err)
	}
	if q.getURLsStmt, err = db.PrepareContext(ctx, GetURLs); err != nil {
		return nil, fmt.Errorf("error preparing query GetURLs: %w", err)
	}
	if q.hasInterruptedSessionStmt, err = db.PrepareContext(ctx, HasInterruptedSession); err != nil {
		return nil, fmt.Errorf("error preparing query HasInterruptedSession: %w", err)
	}
	if q.heartbeatProcessStmt, err = db.PrepareContext(ctx, HeartbeatProcess); err != nil {
		return nil, fmt.Errorf("error preparing query HeartbeatProcess: %w", err)
	}
	if q.insertBatchStmt, err = db.PrepareContext(ctx, InsertBatch); err != nil {
		return nil, fmt.Errorf("error preparing query InsertBatch: %w", err)
	}
	if q.insertDownloadedFileStmt, err = db.PrepareContext(ctx, InsertDownloadedFile); err != nil {
		return nil, fmt.Errorf("error preparing query InsertDownloadedFile: %w", err)
	}
	if q.insertFindingStmt, err = db.PrepareContext(ctx, InsertFinding); err != nil {
		return nil, fmt.Errorf("error preparing query InsertFinding: %w", err)
	}
	if q.insertNoteStmt, err = db.PrepareContext(ctx, InsertNote); err != nil {
		return nil, fmt.Errorf("error preparing query InsertNote: %w", err)
	}
	if q.insertOrIgnoreDNSRecordStmt, err = db.PrepareContext(ctx, InsertOrIgnoreDNSRecord); err != nil {
		return nil, fmt.Errorf("error preparing query InsertOrIgnoreDNSRecord: %w", err)
	}
	if q.insertOrIgnoreIPStmt, err = db.PrepareContext(ctx, InsertOrIgnoreIP); err != nil {
		return nil, fmt.Errorf("error preparing query InsertOrIgnoreIP: %w", err)
	}
	if q.insertOrIgnorePipelineStateStmt, err = db.PrepareContext(ctx, InsertOrIgnorePipelineState); err != nil {
		return nil, fmt.Errorf("error preparing query InsertOrIgnorePipelineState: %w", err)
	}
	if q.insertOrIgnorePortStmt, err = db.PrepareContext(ctx, InsertOrIgnorePort); err != nil {
		return nil, fmt.Errorf("error preparing query InsertOrIgnorePort: %w", err)
	}
	if q.insertOrIgnoreTechStackStmt, err = db.PrepareContext(ctx, InsertOrIgnoreTechStack); err != nil {
		return nil, fmt.Errorf("error preparing query InsertOrIgnoreTechStack: %w", err)
	}
	if q.insertOrIgnoreURLFlagStmt, err = db.PrepareContext(ctx, InsertOrIgnoreURLFlag); err != nil {
		return nil, fmt.Errorf("error preparing query InsertOrIgnoreURLFlag: %w", err)
	}
	if q.insertOrTouchDomainStmt, err = db.PrepareContext(ctx, InsertOrTouchDomain); err != nil {
		return nil, fmt.Errorf("error preparing query InsertOrTouchDomain: %w", err)
	}
	if q.insertOrTouchURLStmt, err = db.PrepareContext(ctx, InsertOrTouchURL); err != nil {
		return nil, fmt.Errorf("error preparing query InsertOrTouchURL: %w", err)
	}
	if q.insertProcessStmt, err = db.PrepareContext(ctx, InsertProcess); err != nil {
		return nil, fmt.Errorf("error preparing query InsertProcess: %w", err)
	}
	if q.insertScopeRuleStmt, err = db.PrepareContext(ctx, InsertScopeRule); err != nil {
		return nil, fmt.Errorf("error preparing query InsertScopeRule: %w", err)
	}
	if q.resetProcessingItemsStmt, err = db.PrepareContext(ctx, ResetProcessingItems); err != nil {
		return nil, fmt.Errorf("error preparing query ResetProcessingItems: %w", err)
	}
	if q.updateDNSRecordStmt, err = db.PrepareContext(ctx, UpdateDNSRecord); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateDNSRecord: %w", err)
	}
	if q.updateDomainLivenessStmt, err = db.PrepareContext(ctx, UpdateDomainLiveness); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateDomainLiveness: %w", err)
	}
	if q.updateNoteStmt, err = db.PrepareContext(ctx, UpdateNote); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateNote: %w", err)
	}
	if q.updatePipelineStateStmt, err = db.PrepareContext(ctx, UpdatePipelineState); err != nil {
		return nil, fmt.Errorf("error preparing query UpdatePipelineState: %w", err)
	}
	if q.updatePortStmt, err = db.PrepareContext(ctx, UpdatePort); err != nil {
		return nil, fmt.Errorf("error preparing query UpdatePort: %w", err)
	}
	if q.updateTechStackStmt, err = db.PrepareContext(ctx, UpdateTechStack); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateTechStack: %w", err)
	}
	if q.updateURLDetailsStmt, err = db.PrepareContext(ctx, UpdateURLDetails); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateURLDetails: %w", err)
	}
	if q.updateURLFlagStmt, err = db.PrepareContext(ctx, UpdateURLFlag); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateURLFlag: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.completeBatchStmt != nil {
		if cerr := q.completeBatchStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing completeBatchStmt: %w", cerr)
		}
	}
	if q.completeProcessStmt != nil {
		if cerr := q.completeProcessStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing completeProcessStmt: %w", cerr)
		}
	}
	if q.countDomainsStmt != nil {
		if cerr := q.countDomainsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countDomainsStmt: %w", cerr)
		}
	}
	if q.countFindingsStmt != nil {
		if cerr := q.countFindingsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countFindingsStmt: %w", cerr)
		}
	}
	if q.countURLsStmt != nil {
		if cerr := q.countURLsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countURLsStmt: %w", cerr)
		}
	}
	if q.deleteNoteStmt != nil {
		if cerr := q.deleteNoteStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteNoteStmt: %w", cerr)
		}
	}
	if q.deleteScopeRuleByPatternStmt != nil {
		if cerr := q.deleteScopeRuleByPatternStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteScopeRuleByPatternStmt: %w", cerr)
		}
	}
	if q.getBatchByIDStmt != nil {
		if cerr := q.getBatchByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBatchByIDStmt: %w", cerr)
		}
	}
	if q.getDNSRecordsByDomainStmt != nil {
		if cerr := q.getDNSRecordsByDomainStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDNSRecordsByDomainStmt: %w", cerr)
		}
	}
	if q.getDomainByNameStmt != nil {
		if cerr := q.getDomainByNameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDomainByNameStmt: %w", cerr)
		}
	}
	if q.getDomainsStmt != nil {
		if cerr := q.getDomainsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDomainsStmt: %w", cerr)
		}
	}
	if q.getDownloadedFilesByURLStmt != nil {
		if cerr := q.getDownloadedFilesByURLStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDownloadedFilesByURLStmt: %w", cerr)
		}
	}
	if q.getFindingsStmt != nil {
		if cerr := q.getFindingsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFindingsStmt: %w", cerr)
		}
	}
	if q.getIPByAddressStmt != nil {
		if cerr := q.getIPByAddressStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getIPByAddressStmt: %w", cerr)
		}
	}
	if q.getLiveDomainsStmt != nil {
		if cerr := q.getLiveDomainsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLiveDomainsStmt: %w", cerr)
		}
	}
	if q.getNotesStmt != nil {
		if cerr := q.getNotesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getNotesStmt: %w", cerr)
		}
	}
	if q.getPendingItemsStmt != nil {
		if cerr := q.getPendingItemsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPendingItemsStmt: %w", cerr)
		}
	}
	if q.getPortsByIPStmt != nil {
		if cerr := q.getPortsByIPStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPortsByIPStmt: %w", cerr)
		}
	}
	if q.getProcessByIDStmt != nil {
		if cerr := q.getProcessByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getProcessByIDStmt: %w", cerr)
		}
	}
	if q.getRunningProcessPIDsStmt != nil {
		if cerr := q.getRunningProcessPIDsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRunningProcessPIDsStmt: %w", cerr)
		}
	}
	if q.getScopeRulesStmt != nil {
		if cerr := q.getScopeRulesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getScopeRulesStmt: %w", cerr)
		}
	}
	if q.getTechStackByDomainStmt != nil {
		if cerr := q.getTechStackByDomainStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTechStackByDomainStmt: %w", cerr)
		}
	}
	if q.getURLByFullURLStmt != nil {
		if cerr := q.getURLByFullURLStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getURLByFullURLStmt: %w", cerr)
		}
	}
	if q.getURLFlagsByURLStmt != nil {
		if cerr := q.getURLFlagsByURLStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getURLFlagsByURLStmt: %w", cerr)
		}
	}
	if q.getURLsStmt != nil {
		if cerr := q.getURLsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getURLsStmt: %w", cerr)
		}
	}
	if q.hasInterruptedSessionStmt != nil {
		if cerr := q.hasInterruptedSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing hasInterruptedSessionStmt: %w", cerr)
		}
	}
	if q.heartbeatProcessStmt != nil {
		if cerr := q.heartbeatProcessStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing heartbeatProcessStmt: %w", cerr)
		}
	}
	if q.insertBatchStmt != nil {
		if cerr := q.insertBatchStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertBatchStmt: %w", cerr)
		}
	}
	if q.insertDownloadedFileStmt != nil {
		if cerr := q.insertDownloadedFileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertDownloadedFileStmt: %w", cerr)
		}
	}
	if q.insertFindingStmt != nil {
		if cerr := q.insertFindingStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertFindingStmt: %w", cerr)
		}
	}
	if q.insertNoteStmt != nil {
		if cerr := q.insertNoteStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertNoteStmt: %w", cerr)
		}
	}
	if q.insertOrIgnoreDNSRecordStmt != nil {
		if cerr := q.insertOrIgnoreDNSRecordStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertOrIgnoreDNSRecordStmt: %w", cerr)
		}
	}
	if q.insertOrIgnoreIPStmt != nil {
		if cerr := q.insertOrIgnoreIPStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertOrIgnoreIPStmt: %w", cerr)
		}
	}
	if q.insertOrIgnorePipelineStateStmt != nil {
		if cerr := q.insertOrIgnorePipelineStateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertOrIgnorePipelineStateStmt: %w", cerr)
		}
	}
	if q.insertOrIgnorePortStmt != nil {
		if cerr := q.insertOrIgnorePortStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertOrIgnorePortStmt: %w", cerr)
		}
	}
	if q.insertOrIgnoreTechStackStmt != nil {
		if cerr := q.insertOrIgnoreTechStackStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertOrIgnoreTechStackStmt: %w", cerr)
		}
	}
	if q.insertOrIgnoreURLFlagStmt != nil {
		if cerr := q.insertOrIgnoreURLFlagStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertOrIgnoreURLFlagStmt: %w", cerr)
		}
	}
	if q.insertOrTouchDomainStmt != nil {
		if cerr := q.insertOrTouchDomainStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertOrTouchDomainStmt: %w", cerr)
		}
	}
	if q.insertOrTouchURLStmt != nil {
		if cerr := q.insertOrTouchURLStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertOrTouchURLStmt: %w", cerr)
		}
	}
	if q.insertProcessStmt != nil {
		if cerr := q.insertProcessStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertProcessStmt: %w", cerr)
		}
	}
	if q.insertScopeRuleStmt != nil {
		if cerr := q.insertScopeRuleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertScopeRuleStmt: %w", cerr)
		}
	}
	if q.resetProcessingItemsStmt != nil {
		if cerr := q.resetProcessingItemsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing resetProcessingItemsStmt: %w", cerr)
		}
	}
	if q.updateDNSRecordStmt != nil {
		if cerr := q.updateDNSRecordStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateDNSRecordStmt: %w", cerr)
		}
	}
	if q.updateDomainLivenessStmt != nil {
		if cerr := q.updateDomainLivenessStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateDomainLivenessStmt: %w", cerr)
		}
	}
	if q.updateNoteStmt != nil {
		if cerr := q.updateNoteStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateNoteStmt: %w", cerr)
		}
	}
	if q.updatePipelineStateStmt != nil {
		if cerr := q.updatePipelineStateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updatePipelineStateStmt: %w", cerr)
		}
	}
	if q.updatePortStmt != nil {
		if cerr := q.updatePortStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updatePortStmt: %w", cerr)
		}
	}
	if q.updateTechStackStmt != nil {
		if cerr := q.updateTechStackStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateTechStackStmt: %w", cerr)
		}
	}
	if q.updateURLDetailsStmt != nil {
		if cerr := q.updateURLDetailsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateURLDetailsStmt: %w", cerr)
		}
	}
	if q.updateURLFlagStmt != nil {
		if cerr := q.updateURLFlagStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateURLFlagStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                              DBTX
	tx                              *sql.Tx
	completeBatchStmt               *sql.Stmt
	completeProcessStmt             *sql.Stmt
	countDomainsStmt                *sql.Stmt
	countFindingsStmt               *sql.Stmt
	countURLsStmt                   *sql.Stmt
	deleteNoteStmt                  *sql.Stmt
	deleteScopeRuleByPatternStmt    *sql.Stmt
	getBatchByIDStmt                *sql.Stmt
	getDNSRecordsByDomainStmt       *sql.Stmt
	getDomainByNameStmt             *sql.Stmt
	getDomainsStmt                  *sql.Stmt
	getDownloadedFilesByURLStmt     *sql.Stmt
	getFindingsStmt                 *sql.Stmt
	getIPByAddressStmt              *sql.Stmt
	getLiveDomainsStmt              *sql.Stmt
	getNotesStmt                    *sql.Stmt
	getPendingItemsStmt             *sql.Stmt
	getPortsByIPStmt                *sql.Stmt
	getProcessByIDStmt              *sql.Stmt
	getRunningProcessPIDsStmt       *sql.Stmt
	getScopeRulesStmt               *sql.Stmt
	getTechStackByDomainStmt        *sql.Stmt
	getURLByFullURLStmt             *sql.Stmt
	getURLFlagsByURLStmt            *sql.Stmt
	getURLsStmt                     *sql.Stmt
	hasInterruptedSessionStmt       *sql.Stmt
	heartbeatProcessStmt            *sql.Stmt
	insertBatchStmt                 *sql.Stmt
	insertDownloadedFileStmt        *sql.Stmt
	insertFindingStmt               *sql.Stmt
	insertNoteStmt                  *sql.Stmt
	insertOrIgnoreDNSRecordStmt     *sql.Stmt
	insertOrIgnoreIPStmt            *sql.Stmt
	insertOrIgnorePipelineStateStmt *sql.Stmt
	insertOrIgnorePortStmt          *sql.Stmt
	insertOrIgnoreTechStackStmt     *sql.Stmt
	insertOrIgnoreURLFlagStmt       *sql.Stmt
	insertOrTouchDomainStmt         *sql.Stmt
	insertOrTouchURLStmt            *sql.Stmt
	insertProcessStmt               *sql.Stmt
	insertScopeRuleStmt             *sql.Stmt
	resetProcessingItemsStmt        *sql.Stmt
	updateDNSRecordStmt             *sql.Stmt
	updateDomainLivenessStmt        *sql.Stmt
	updateNoteStmt                  *sql.Stmt
	updatePipelineStateStmt         *sql.Stmt
	updatePortStmt                  *sql.Stmt
	updateTechStackStmt             *sql.Stmt
	updateURLDetailsStmt            *sql.Stmt
	updateURLFlagStmt               *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                              tx,
		tx:                              tx,
		completeBatchStmt:               q.completeBatchStmt,
		completeProcessStmt:             q.completeProcessStmt,
		countDomainsStmt:                q.countDomainsStmt,
		countFindingsStmt:               q.countFindingsStmt,
		countURLsStmt:                   q.countURLsStmt,
		deleteNoteStmt:                  q.deleteNoteStmt,
		deleteScopeRuleByPatternStmt:    q.deleteScopeRuleByPatternStmt,
		getBatchByIDStmt:                q.getBatchByIDStmt,
		getDNSRecordsByDomainStmt:       q.getDNSRecordsByDomainStmt,
		getDomainByNameStmt:             q.getDomainByNameStmt,
		getDomainsStmt:                  q.getDomainsStmt,
		getDownloadedFilesByURLStmt:     q.getDownloadedFilesByURLStmt,
		getFindingsStmt:                 q.getFindingsStmt,
		getIPByAddressStmt:              q.getIPByAddressStmt,
		getLiveDomainsStmt:              q.getLiveDomainsStmt,
		getNotesStmt:                    q.getNotesStmt,
		getPendingItemsStmt:             q.getPendingItemsStmt,
		getPortsByIPStmt:                q.getPortsByIPStmt,
		getProcessByIDStmt:              q.getProcessByIDStmt,
		getRunningProcessPIDsStmt:       q.getRunningProcessPIDsStmt,
		getScopeRulesStmt:               q.getScopeRulesStmt,
		getTechStackByDomainStmt:        q.getTechStackByDomainStmt,
		getURLByFullURLStmt:             q.getURLByFullURLStmt,
		getURLFlagsByURLStmt:            q.getURLFlagsByURLStmt,
		getURLsStmt:                     q.getURLsStmt,
		hasInterruptedSessionStmt:       q.hasInterruptedSessionStmt,
		heartbeatProcessStmt:            q.heartbeatProcessStmt,
		insertBatchStmt:                 q.insertBatchStmt,
		insertDownloadedFileStmt:        q.insertDownloadedFileStmt,
		insertFindingStmt:               q.insertFindingStmt,
		insertNoteStmt:                  q.insertNoteStmt,
		insertOrIgnoreDNSRecordStmt:     q.insertOrIgnoreDNSRecordStmt,
		insertOrIgnoreIPStmt:            q.insertOrIgnoreIPStmt,
		insertOrIgnorePipelineStateStmt: q.insertOrIgnorePipelineStateStmt,
		insertOrIgnorePortStmt:          q.insertOrIgnorePortStmt,
		insertOrIgnoreTechStackStmt:     q.insertOrIgnoreTechStackStmt,
		insertOrIgnoreURLFlagStmt:       q.insertOrIgnoreURLFlagStmt,
		insertOrTouchDomainStmt:         q.insertOrTouchDomainStmt,
		insertOrTouchURLStmt:            q.insertOrTouchURLStmt,
		insertProcessStmt:               q.insertProcessStmt,
		insertScopeRuleStmt:             q.insertScopeRuleStmt,
		resetProcessingItemsStmt:        q.resetProcessingItemsStmt,
		updateDNSRecordStmt:             q.updateDNSRecordStmt,
		updateDomainLivenessStmt:        q.updateDomainLivenessStmt,
		updateNoteStmt:                  q.updateNoteStmt,
		updatePipelineStateStmt:         q.updatePipelineStateStmt,
		updatePortStmt:                  q.updatePortStmt,
		updateTechStackStmt:             q.updateTechStackStmt,
		updateURLDetailsStmt:            q.updateURLDetailsStmt,
		updateURLFlagStmt:               q.updateURLFlagStmt,
	}
}
