// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Batch struct {
	ID          int64        `db:"id"`
	NodeID      string       `db:"node_id"`
	ItemCount   int64        `db:"item_count"`
	Status      string       `db:"status"`
	CreatedAt   time.Time    `db:"created_at"`
	CompletedAt sql.NullTime `db:"completed_at"`
}

type DnsRecord struct {
	ID         int64  `db:"id"`
	DomainID   int64  `db:"domain_id"`
	RecordType string `db:"record_type"`
	Value      string `db:"value"`
	Ttl        *int64 `db:"ttl"`
	Source     string `db:"source"`
}

type Domain struct {
	ID        int64     `db:"id"`
	Name      string    `db:"name"`
	Source    string    `db:"source"`
	IsLive    *bool     `db:"is_live"`
	Ip        *string   `db:"ip"`
	BatchID   *int64    `db:"batch_id"`
	CreatedAt time.Time `db:"created_at"`
	UpdatedAt time.Time `db:"updated_at"`
}

type DownloadedFile struct {
	ID        int64     `db:"id"`
	UrlID     int64     `db:"url_id"`
	FilePath  string    `db:"file_path"`
	FileType  string    `db:"file_type"`
	SizeBytes *int64    `db:"size_bytes"`
	Sha256    *string   `db:"sha256"`
	CreatedAt time.Time `db:"created_at"`
}

type Finding struct {
	ID          int64     `db:"id"`
	DomainID    *int64    `db:"domain_id"`
	UrlID       *int64    `db:"url_id"`
	Scanner     string    `db:"scanner"`
	Severity    *string   `db:"severity"`
	Title       string    `db:"title"`
	Description *string   `db:"description"`
	Evidence    *string   `db:"evidence"`
	CreatedAt   time.Time `db:"created_at"`
}

type Ip struct {
	ID        int64     `db:"id"`
	Address   string    `db:"address"`
	CreatedAt time.Time `db:"created_at"`
}

type PipelineState struct {
	ID          int64        `db:"id"`
	ItemType    string       `db:"item_type"`
	ItemID      int64        `db:"item_id"`
	NodeID      string       `db:"node_id"`
	Status      string       `db:"status"`
	StartedAt   sql.NullTime `db:"started_at"`
	CompletedAt sql.NullTime `db:"completed_at"`
	Error       *string      `db:"error"`
}

type Port struct {
	ID       int64   `db:"id"`
	IpID     int64   `db:"ip_id"`
	Port     int64   `db:"port"`
	Protocol string  `db:"protocol"`
	Service  *string `db:"service"`
	Banner   *string `db:"banner"`
	Source   string  `db:"source"`
}

type Process struct {
	ID            int64        `db:"id"`
	Name          string       `db:"name"`
	Command       string       `db:"command"`
	Pid           *int64       `db:"pid"`
	NodeID        string       `db:"node_id"`
	BatchID       *int64       `db:"batch_id"`
	Status        string       `db:"status"`
	ExitCode      *int64       `db:"exit_code"`
	StdoutPath    *string      `db:"stdout_path"`
	StderrPath    *string      `db:"stderr_path"`
	StartedAt     time.Time    `db:"started_at"`
	CompletedAt   sql.NullTime `db:"completed_at"`
	LastHeartbeat time.Time    `db:"last_heartbeat"`
}

type ScopeRule struct {
	ID        int64     `db:"id"`
	Pattern   string    `db:"pattern"`
	Type      string    `db:"type"`
	InScope   bool      `db:"in_scope"`
	CreatedAt time.Time `db:"created_at"`
}

type Techstack struct {
	ID         int64   `db:"id"`
	DomainID   int64   `db:"domain_id"`
	Technology string  `db:"technology"`
	Version    *string `db:"version"`
	Category   *string `db:"category"`
	Source     string  `db:"source"`
}

type Url struct {
	ID          int64     `db:"id"`
	FullUrl     string    `db:"full_url"`
	DomainID    *int64    `db:"domain_id"`
	Path        *string   `db:"path"`
	QueryString *string   `db:"query_string"`
	StatusCode  *int64    `db:"status_code"`
	ContentType *string   `db:"content_type"`
	Source      string    `db:"source"`
	BatchID     *int64    `db:"batch_id"`
	CreatedAt   time.Time `db:"created_at"`
	UpdatedAt   time.Time `db:"updated_at"`
}

type UrlFlag struct {
	ID        int64   `db:"id"`
	UrlID     int64   `db:"url_id"`
	FlagType  string  `db:"flag_type"`
	FlagValue *string `db:"flag_value"`
	Source    string  `db:"source"`
}
