// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const CompleteBatch = `-- name: CompleteBatch :exec
= ?;

UPDATE batches SET status = ?, completed_at = CURRENT_TIMESTAMP WHERE id
`

type CompleteBatchParams struct {
	Status string `db:"status"`
	ID     int64  `db:"id"`
}

func (q *Queries) CompleteBatch(ctx context.Context, arg CompleteBatchParams) error {
	_, err := q.exec(ctx, q.completeBatchStmt, CompleteBatch, arg.Status, arg.ID)
	return err
}

const CompleteProcess = `-- name: CompleteProcess :exec
= ?;

UPDATE processes SET status = ?, exit_code = ?, completed_at = CURRENT_TIMESTAMP WHERE id
`

type CompleteProcessParams struct {
	Status   string `db:"status"`
	ExitCode *int64 `db:"exit_code"`
	ID       int64  `db:"id"`
}

func (q *Queries) CompleteProcess(ctx context.Context, arg CompleteProcessParams) error {
	_, err := q.exec(ctx, q.completeProcessStmt, CompleteProcess, arg.Status, arg.ExitCode, arg.ID)
	return err
}

const CountDomains = `-- name: CountDomains :one
T ?;

SELECT COUNT(*) FROM dom
`

func (q *Queries) CountDomains(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countDomainsStmt, CountDomains)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountFindings = `-- name: CountFindings :one
T ?;

SELECT COUNT(*) FROM find
`

func (q *Queries) CountFindings(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countFindingsStmt, CountFindings)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountURLs = `-- name: CountURLs :one
T ?;

SELECT COUNT(*) FROM
`

func (q *Queries) CountURLs(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countURLsStmt, CountURLs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const DeleteNote = `-- name: DeleteNote :exec
= ?;

DELETE FROM notes WHERE id
`

func (q *Queries) DeleteNote(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deleteNoteStmt, DeleteNote, id)
	return err
}

const DeleteScopeRuleByPattern = `-- name: DeleteScopeRuleByPattern :exec
ASC;

DELETE FROM scope_rules WHERE pattern
`

func (q *Queries) DeleteScopeRuleByPattern(ctx context.Context, pattern string) error {
	_, err := q.exec(ctx, q.deleteScopeRuleByPatternStmt, DeleteScopeRuleByPattern, pattern)
	return err
}

const GetBatchByID = `-- name: GetBatchByID :one
g');

SELECT id, node_id, item_count, status, created_at, completed_at FROM batches WHERE id
`

func (q *Queries) GetBatchByID(ctx context.Context, id int64) (Batch, error) {
	row := q.queryRow(ctx, q.getBatchByIDStmt, GetBatchByID, id)
	var i Batch
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.ItemCount,
		&i.Status,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const GetDNSRecordsByDomain = `-- name: GetDNSRecordsByDomain :many
= ?;

SELECT id, domain_id, record_type, value, ttl, source FROM dns_records WHERE domain_id
`

func (q *Queries) GetDNSRecordsByDomain(ctx context.Context, domainID int64) ([]DnsRecord, error) {
	rows, err := q.query(ctx, q.getDNSRecordsByDomainStmt, GetDNSRecordsByDomain, domainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DnsRecord{}
	for rows.Next() {
		var i DnsRecord
		if err := rows.Scan(
			&i.ID,
			&i.DomainID,
			&i.RecordType,
			&i.Value,
			&i.Ttl,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetDomainByName = `-- name: GetDomainByName :one
AMP;

SELECT id, name, source, is_live, ip, batch_id, created_at, updated_at
FROM domains WHERE name
`

func (q *Queries) GetDomainByName(ctx context.Context, name string) (Domain, error) {
	row := q.queryRow(ctx, q.getDomainByNameStmt, GetDomainByName, name)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Source,
		&i.IsLive,
		&i.Ip,
		&i.BatchID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetDomains = `-- name: GetDomains :many
= ?;

SELECT id, name, source, is_live, ip, batch_id, created_at, updated_at
FROM domains ORDER BY created_at DESC LIMIT ? OFFS
`

type GetDomainsParams struct {
	Limit  int64 `db:"limit"`
	Offset int64 `db:"offset"`
}

func (q *Queries) GetDomains(ctx context.Context, arg GetDomainsParams) ([]Domain, error) {
	rows, err := q.query(ctx, q.getDomainsStmt, GetDomains, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Domain{}
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Source,
			&i.IsLive,
			&i.Ip,
			&i.BatchID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetDownloadedFilesByURL = `-- name: GetDownloadedFilesByURL :many
?);

SELECT id, url_id, file_path, file_type, size_bytes, sha256, created_at
FROM downloaded_files WHERE url_id
`

func (q *Queries) GetDownloadedFilesByURL(ctx context.Context, urlID int64) ([]DownloadedFile, error) {
	rows, err := q.query(ctx, q.getDownloadedFilesByURLStmt, GetDownloadedFilesByURL, urlID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DownloadedFile{}
	for rows.Next() {
		var i DownloadedFile
		if err := rows.Scan(
			&i.ID,
			&i.UrlID,
			&i.FilePath,
			&i.FileType,
			&i.SizeBytes,
			&i.Sha256,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetFindings = `-- name: GetFindings :many
?);

SELECT id, domain_id, url_id, scanner, severity, title, description, evidence, created_at
FROM findings ORDER BY created_at DESC LIMIT ? OFFS
`

type GetFindingsParams struct {
	Limit  int64 `db:"limit"`
	Offset int64 `db:"offset"`
}

func (q *Queries) GetFindings(ctx context.Context, arg GetFindingsParams) ([]Finding, error) {
	rows, err := q.query(ctx, q.getFindingsStmt, GetFindings, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Finding{}
	for rows.Next() {
		var i Finding
		if err := rows.Scan(
			&i.ID,
			&i.DomainID,
			&i.UrlID,
			&i.Scanner,
			&i.Severity,
			&i.Title,
			&i.Description,
			&i.Evidence,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetIPByAddress = `-- name: GetIPByAddress :one
(?);

SELECT id, address, created_at FROM ips WHERE address
`

func (q *Queries) GetIPByAddress(ctx context.Context, address string) (Ip, error) {
	row := q.queryRow(ctx, q.getIPByAddressStmt, GetIPByAddress, address)
	var i Ip
	err := row.Scan(&i.ID, &i.Address, &i.CreatedAt)
	return i, err
}

const GetLiveDomains = `-- name: GetLiveDomains :many
T ?;

SELECT id, name, source, is_live, ip, batch_id, created_at, updated_at
FROM domains WHERE is_live = 1 ORDER BY created_at DESC LIMIT ? OFFS
`

type GetLiveDomainsParams struct {
	Limit  int64 `db:"limit"`
	Offset int64 `db:"offset"`
}

func (q *Queries) GetLiveDomains(ctx context.Context, arg GetLiveDomainsParams) ([]Domain, error) {
	rows, err := q.query(ctx, q.getLiveDomainsStmt, GetLiveDomains, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Domain{}
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Source,
			&i.IsLive,
			&i.Ip,
			&i.BatchID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetNotes = `-- name: GetNotes :many
(?);

SELECT id, content, created_at, updated_at FROM notes ORDER BY created_at
`

func (q *Queries) GetNotes(ctx context.Context) ([]Note, error) {
	rows, err := q.query(ctx, q.getNotesStmt, GetNotes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetPendingItems = `-- name: GetPendingItems :many
= ?;

SELECT id, item_type, item_id, node_id, status, started_at, completed_at, error
FROM pipeline_state
WHERE node_id = ? AND item_type = ? AND status = 'pending'
ORDER BY id ASC
LIM
`

type GetPendingItemsParams struct {
	NodeID   string `db:"node_id"`
	ItemType string `db:"item_type"`
	Limit    int64  `db:"limit"`
}

func (q *Queries) GetPendingItems(ctx context.Context, arg GetPendingItemsParams) ([]PipelineState, error) {
	rows, err := q.query(ctx, q.getPendingItemsStmt, GetPendingItems, arg.NodeID, arg.ItemType, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PipelineState{}
	for rows.Next() {
		var i PipelineState
		if err := rows.Scan(
			&i.ID,
			&i.ItemType,
			&i.ItemID,
			&i.NodeID,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetPortsByIP = `-- name: GetPortsByIP :many
= ?;

SELECT id, ip_id, port, protocol, service, banner, source FROM ports WHERE ip_id
`

func (q *Queries) GetPortsByIP(ctx context.Context, ipID int64) ([]Port, error) {
	rows, err := q.query(ctx, q.getPortsByIPStmt, GetPortsByIP, ipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Port{}
	for rows.Next() {
		var i Port
		if err := rows.Scan(
			&i.ID,
			&i.IpID,
			&i.Port,
			&i.Protocol,
			&i.Service,
			&i.Banner,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetProcessByID = `-- name: GetProcessByID :one
?);

SELECT id, name, command, pid, node_id, batch_id, status, exit_code,
       stdout_path, stderr_path, started_at, completed_at, last_heartbeat
FROM processes WHERE id
`

func (q *Queries) GetProcessByID(ctx context.Context, id int64) (Process, error) {
	row := q.queryRow(ctx, q.getProcessByIDStmt, GetProcessByID, id)
	var i Process
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Command,
		&i.Pid,
		&i.NodeID,
		&i.BatchID,
		&i.Status,
		&i.ExitCode,
		&i.StdoutPath,
		&i.StderrPath,
		&i.StartedAt,
		&i.CompletedAt,
		&i.LastHeartbeat,
	)
	return i, err
}

const GetRunningProcessPIDs = `-- name: GetRunningProcessPIDs :many
= ?;

SELECT pid FROM processes WHERE status = 'running' AND pid IS NOT
`

func (q *Queries) GetRunningProcessPIDs(ctx context.Context) ([]*int64, error) {
	rows, err := q.query(ctx, q.getRunningProcessPIDsStmt, GetRunningProcessPIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*int64{}
	for rows.Next() {
		var pid *int64
		if err := rows.Scan(&pid); err != nil {
			return nil, err
		}
		items = append(items, pid)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetScopeRules = `-- name: GetScopeRules :many
?);

SELECT id, pattern, type, in_scope, created_at FROM scope_rules ORDER BY in_scope ASC, id
`

func (q *Queries) GetScopeRules(ctx context.Context) ([]ScopeRule, error) {
	rows, err := q.query(ctx, q.getScopeRulesStmt, GetScopeRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScopeRule{}
	for rows.Next() {
		var i ScopeRule
		if err := rows.Scan(
			&i.ID,
			&i.Pattern,
			&i.Type,
			&i.InScope,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetTechStackByDomain = `-- name: GetTechStackByDomain :many
= ?;

SELECT id, domain_id, technology, version, category, source FROM techstack WHERE domain_id
`

func (q *Queries) GetTechStackByDomain(ctx context.Context, domainID int64) ([]Techstack, error) {
	rows, err := q.query(ctx, q.getTechStackByDomainStmt, GetTechStackByDomain, domainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Techstack{}
	for rows.Next() {
		var i Techstack
		if err := rows.Scan(
			&i.ID,
			&i.DomainID,
			&i.Technology,
			&i.Version,
			&i.Category,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetURLByFullURL = `-- name: GetURLByFullURL :one
AMP;

SELECT id, full_url, domain_id, path, query_string, status_code, content_type,
       source, batch_id, created_at, updated_at
FROM urls WHERE full_url
`

func (q *Queries) GetURLByFullURL(ctx context.Context, fullUrl string) (Url, error) {
	row := q.queryRow(ctx, q.getURLByFullURLStmt, GetURLByFullURL, fullUrl)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.FullUrl,
		&i.DomainID,
		&i.Path,
		&i.QueryString,
		&i.StatusCode,
		&i.ContentType,
		&i.Source,
		&i.BatchID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetURLFlagsByURL = `-- name: GetURLFlagsByURL :many
= ?;

SELECT id, url_id, flag_type, flag_value, source FROM url_flags WHERE url_id
`

func (q *Queries) GetURLFlagsByURL(ctx context.Context, urlID int64) ([]UrlFlag, error) {
	rows, err := q.query(ctx, q.getURLFlagsByURLStmt, GetURLFlagsByURL, urlID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UrlFlag{}
	for rows.Next() {
		var i UrlFlag
		if err := rows.Scan(
			&i.ID,
			&i.UrlID,
			&i.FlagType,
			&i.FlagValue,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetURLs = `-- name: GetURLs :many
= ?;

SELECT id, full_url, domain_id, path, query_string, status_code, content_type,
       source, batch_id, created_at, updated_at
FROM urls ORDER BY created_at DESC LIMIT ? OFFS
`

type GetURLsParams struct {
	Limit  int64 `db:"limit"`
	Offset int64 `db:"offset"`
}

func (q *Queries) GetURLs(ctx context.Context, arg GetURLsParams) ([]Url, error) {
	rows, err := q.query(ctx, q.getURLsStmt, GetURLs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Url{}
	for rows.Next() {
		var i Url
		if err := rows.Scan(
			&i.ID,
			&i.FullUrl,
			&i.DomainID,
			&i.Path,
			&i.QueryString,
			&i.StatusCode,
			&i.ContentType,
			&i.Source,
			&i.BatchID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const HasInterruptedSession = `-- name: HasInterruptedSession :one
ng';

SELECT COUNT(*) FROM pipeline_state WHERE status = 'process
`

func (q *Queries) HasInterruptedSession(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.hasInterruptedSessionStmt, HasInterruptedSession)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const HeartbeatProcess = `-- name: HeartbeatProcess :exec
= ?;
UPDATE processes
SET last_heartbeat = CURRENT_TIMESTAMP
WHERE id
`

func (q *Queries) HeartbeatProcess(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.heartbeatProcessStmt, HeartbeatProcess, id)
	return err
}

const InsertBatch = `-- name: InsertBatch :exec
= ?;


INSERT INTO batches (node_id, item_count, status) VALUES (?, ?, 'processi
`

type InsertBatchParams struct {
	NodeID    string `db:"node_id"`
	ItemCount int64  `db:"item_count"`
}

// ============================================================
// batches
// ============================================================
func (q *Queries) InsertBatch(ctx context.Context, arg InsertBatchParams) error {
	_, err := q.exec(ctx, q.insertBatchStmt, InsertBatch, arg.NodeID, arg.ItemCount)
	return err
}

const InsertDownloadedFile = `-- name: InsertDownloadedFile :exec
= ?;


INSERT INTO downloaded_files (url_id, file_path, file_type, size_bytes, sha256) VALUES (?, ?, ?, ?
`

type InsertDownloadedFileParams struct {
	UrlID     int64   `db:"url_id"`
	FilePath  string  `db:"file_path"`
	FileType  string  `db:"file_type"`
	SizeBytes *int64  `db:"size_bytes"`
	Sha256    *string `db:"sha256"`
}

// ============================================================
// downloaded_files
// ============================================================
func (q *Queries) InsertDownloadedFile(ctx context.Context, arg InsertDownloadedFileParams) error {
	_, err := q.exec(ctx, q.insertDownloadedFileStmt, InsertDownloadedFile,
		arg.UrlID,
		arg.FilePath,
		arg.FileType,
		arg.SizeBytes,
		arg.Sha256,
	)
	return err
}

const InsertFinding = `-- name: InsertFinding :exec
= ?;


INSERT INTO findings (domain_id, url_id, scanner, severity, title, description, evidence)
VALUES (?, ?, ?, ?, ?, ?
`

type InsertFindingParams struct {
	DomainID    *int64  `db:"domain_id"`
	UrlID       *int64  `db:"url_id"`
	Scanner     string  `db:"scanner"`
	Severity    *string `db:"severity"`
	Title       string  `db:"title"`
	Description *string `db:"description"`
	Evidence    *string `db:"evidence"`
}

// ============================================================
// findings
// ============================================================
func (q *Queries) InsertFinding(ctx context.Context, arg InsertFindingParams) error {
	_, err := q.exec(ctx, q.insertFindingStmt, InsertFinding,
		arg.DomainID,
		arg.UrlID,
		arg.Scanner,
		arg.Severity,
		arg.Title,
		arg.Description,
		arg.Evidence,
	)
	return err
}

const InsertNote = `-- name: InsertNote :exec
= ?;


INSERT INTO notes (content) VALUES
`

// ============================================================
// notes
// ============================================================
func (q *Queries) InsertNote(ctx context.Context, content string) error {
	_, err := q.exec(ctx, q.insertNoteStmt, InsertNote, content)
	return err
}

const InsertOrIgnoreDNSRecord = `-- name: InsertOrIgnoreDNSRecord :exec
ng';


INSERT OR IGNORE INTO dns_records (domain_id, record_type, value, ttl, source) VALUES (?, ?, ?, ?
`

type InsertOrIgnoreDNSRecordParams struct {
	DomainID   int64  `db:"domain_id"`
	RecordType string `db:"record_type"`
	Value      string `db:"value"`
	Ttl        *int64 `db:"ttl"`
	Source     string `db:"source"`
}

// ============================================================
// dns_records
// ============================================================
func (q *Queries) InsertOrIgnoreDNSRecord(ctx context.Context, arg InsertOrIgnoreDNSRecordParams) error {
	_, err := q.exec(ctx, q.insertOrIgnoreDNSRecordStmt, InsertOrIgnoreDNSRecord,
		arg.DomainID,
		arg.RecordType,
		arg.Value,
		arg.Ttl,
		arg.Source,
	)
	return err
}

const InsertOrIgnoreIP = `-- name: InsertOrIgnoreIP :exec
= ?;


INSERT OR IGNORE INTO ips (address) VALUES
`

// ============================================================
// ips
// ============================================================
func (q *Queries) InsertOrIgnoreIP(ctx context.Context, address string) error {
	_, err := q.exec(ctx, q.insertOrIgnoreIPStmt, InsertOrIgnoreIP, address)
	return err
}

const InsertOrIgnorePipelineState = `-- name: InsertOrIgnorePipelineState :exec
ULL;

INSERT OR IGNORE INTO pipeline_state (item_type, item_id, node_id, status)
VALUES (?, ?, ?, 'pendi
`

type InsertOrIgnorePipelineStateParams struct {
	ItemType string `db:"item_type"`
	ItemID   int64  `db:"item_id"`
	NodeID   string `db:"node_id"`
}

// ============================================================
// pipeline_state
// ============================================================
func (q *Queries) InsertOrIgnorePipelineState(ctx context.Context, arg InsertOrIgnorePipelineStateParams) error {
	_, err := q.exec(ctx, q.insertOrIgnorePipelineStateStmt, InsertOrIgnorePipelineState, arg.ItemType, arg.ItemID, arg.NodeID)
	return err
}

const InsertOrIgnorePort = `-- name: InsertOrIgnorePort :exec
= ?;


INSERT OR IGNORE INTO ports (ip_id, port, protocol, service, banner, source)
VALUES (?, ?, ?, ?, ?
`

type InsertOrIgnorePortParams struct {
	IpID     int64   `db:"ip_id"`
	Port     int64   `db:"port"`
	Protocol string  `db:"protocol"`
	Service  *string `db:"service"`
	Banner   *string `db:"banner"`
	Source   string  `db:"source"`
}

// ============================================================
// ports
// ============================================================
func (q *Queries) InsertOrIgnorePort(ctx context.Context, arg InsertOrIgnorePortParams) error {
	_, err := q.exec(ctx, q.insertOrIgnorePortStmt, InsertOrIgnorePort,
		arg.IpID,
		arg.Port,
		arg.Protocol,
		arg.Service,
		arg.Banner,
		arg.Source,
	)
	return err
}

const InsertOrIgnoreTechStack = `-- name: InsertOrIgnoreTechStack :exec
= ?;


INSERT OR IGNORE INTO techstack (domain_id, technology, version, category, source)
VALUES (?, ?, ?, ?
`

type InsertOrIgnoreTechStackParams struct {
	DomainID   int64   `db:"domain_id"`
	Technology string  `db:"technology"`
	Version    *string `db:"version"`
	Category   *string `db:"category"`
	Source     string  `db:"source"`
}

// ============================================================
// techstack
// ============================================================
func (q *Queries) InsertOrIgnoreTechStack(ctx context.Context, arg InsertOrIgnoreTechStackParams) error {
	_, err := q.exec(ctx, q.insertOrIgnoreTechStackStmt, InsertOrIgnoreTechStack,
		arg.DomainID,
		arg.Technology,
		arg.Version,
		arg.Category,
		arg.Source,
	)
	return err
}

const InsertOrIgnoreURLFlag = `-- name: InsertOrIgnoreURLFlag :exec
= ?;


INSERT OR IGNORE INTO url_flags (url_id, flag_type, flag_value, source) VALUES (?, ?, ?
`

type InsertOrIgnoreURLFlagParams struct {
	UrlID     int64   `db:"url_id"`
	FlagType  string  `db:"flag_type"`
	FlagValue *string `db:"flag_value"`
	Source    string  `db:"source"`
}

// ============================================================
// url_flags
// ============================================================
func (q *Queries) InsertOrIgnoreURLFlag(ctx context.Context, arg InsertOrIgnoreURLFlagParams) error {
	_, err := q.exec(ctx, q.insertOrIgnoreURLFlagStmt, InsertOrIgnoreURLFlag,
		arg.UrlID,
		arg.FlagType,
		arg.FlagValue,
		arg.Source,
	)
	return err
}

const InsertOrTouchDomain = `-- name: InsertOrTouchDomain :exec
= ?;


INSERT INTO domains (name, source, batch_id) VALUES (?, ?, ?)
ON CONFLICT(name) DO UPDATE SET updated_at = CURRENT_TIMES
`

type InsertOrTouchDomainParams struct {
	Name    string `db:"name"`
	Source  string `db:"source"`
	BatchID *int64 `db:"batch_id"`
}

// ============================================================
// domains
// ============================================================
func (q *Queries) InsertOrTouchDomain(ctx context.Context, arg InsertOrTouchDomainParams) error {
	_, err := q.exec(ctx, q.insertOrTouchDomainStmt, InsertOrTouchDomain, arg.Name, arg.Source, arg.BatchID)
	return err
}

const InsertOrTouchURL = `-- name: InsertOrTouchURL :exec
= ?;


INSERT INTO urls (full_url, source, domain_id, batch_id) VALUES (?, ?, ?, ?)
ON CONFLICT(full_url) DO UPDATE SET updated_at = CURRENT_TIMES
`

type InsertOrTouchURLParams struct {
	FullUrl  string `db:"full_url"`
	Source   string `db:"source"`
	DomainID *int64 `db:"domain_id"`
	BatchID  *int64 `db:"batch_id"`
}

// ============================================================
// urls
// ============================================================
func (q *Queries) InsertOrTouchURL(ctx context.Context, arg InsertOrTouchURLParams) error {
	_, err := q.exec(ctx, q.insertOrTouchURLStmt, InsertOrTouchURL,
		arg.FullUrl,
		arg.Source,
		arg.DomainID,
		arg.BatchID,
	)
	return err
}

const InsertProcess = `-- name: InsertProcess :exec
ngs;


INSERT INTO processes (name, command, pid, node_id, batch_id, status, stdout_path, stderr_path)
VALUES (?, ?, ?, ?, ?, 'running', ?
`

type InsertProcessParams struct {
	Name       string  `db:"name"`
	Command    string  `db:"command"`
	Pid        *int64  `db:"pid"`
	NodeID     string  `db:"node_id"`
	BatchID    *int64  `db:"batch_id"`
	StdoutPath *string `db:"stdout_path"`
	StderrPath *string `db:"stderr_path"`
}

// ============================================================
// processes
// ============================================================
func (q *Queries) InsertProcess(ctx context.Context, arg InsertProcessParams) error {
	_, err := q.exec(ctx, q.insertProcessStmt, InsertProcess,
		arg.Name,
		arg.Command,
		arg.Pid,
		arg.NodeID,
		arg.BatchID,
		arg.StdoutPath,
		arg.StderrPath,
	)
	return err
}

const InsertScopeRule = `-- name: InsertScopeRule :exec


INSERT INTO scope_rules (pattern, type, in_scope) VALUES (?, ?
`

type InsertScopeRuleParams struct {
	Pattern string `db:"pattern"`
	Type    string `db:"type"`
	InScope bool   `db:"in_scope"`
}

// Queries for paravizor store.
// All parameters use ? placeholders — never interpolated — making injection impossible.
// Note: sqlc's SQLite parser does not support RETURNING or ON CONFLICT...DO UPDATE,
// so upserts use INSERT OR IGNORE + UPDATE, and inserted IDs are retrieved via last_insert_rowid().
// ============================================================
// scope_rules
// ============================================================
func (q *Queries) InsertScopeRule(ctx context.Context, arg InsertScopeRuleParams) error {
	_, err := q.exec(ctx, q.insertScopeRuleStmt, InsertScopeRule, arg.Pattern, arg.Type, arg.InScope)
	return err
}

const ResetProcessingItems = `-- name: ResetProcessingItems :execresult
T ?;

UPDATE pipeline_state SET status = 'pending', started_at = NULL WHERE status = 'process
`

func (q *Queries) ResetProcessingItems(ctx context.Context) (sql.Result, error) {
	return q.exec(ctx, q.resetProcessingItemsStmt, ResetProcessingItems)
}

const UpdateDNSRecord = `-- name: UpdateDNSRecord :exec
?);

UPDATE dns_records SET ttl = ?, source = ?
WHERE domain_id = ? AND record_type = ? AND value
`

type UpdateDNSRecordParams struct {
	Ttl        *int64 `db:"ttl"`
	Source     string `db:"source"`
	DomainID   int64  `db:"domain_id"`
	RecordType string `db:"record_type"`
	Value      string `db:"value"`
}

func (q *Queries) UpdateDNSRecord(ctx context.Context, arg UpdateDNSRecordParams) error {
	_, err := q.exec(ctx, q.updateDNSRecordStmt, UpdateDNSRecord,
		arg.Ttl,
		arg.Source,
		arg.DomainID,
		arg.RecordType,
		arg.Value,
	)
	return err
}

const UpdateDomainLiveness = `-- name: UpdateDomainLiveness :exec
ins;

UPDATE domains SET is_live = ?, ip = ?, updated_at = CURRENT_TIMESTAMP WHERE id
`

type UpdateDomainLivenessParams struct {
	IsLive *bool   `db:"is_live"`
	Ip     *string `db:"ip"`
	ID     int64   `db:"id"`
}

func (q *Queries) UpdateDomainLiveness(ctx context.Context, arg UpdateDomainLivenessParams) error {
	_, err := q.exec(ctx, q.updateDomainLivenessStmt, UpdateDomainLiveness, arg.IsLive, arg.Ip, arg.ID)
	return err
}

const UpdateNote = `-- name: UpdateNote :exec
ESC;

UPDATE notes SET content = ?, updated_at = CURRENT_TIMESTAMP WHERE id
`

type UpdateNoteParams struct {
	Content string `db:"content"`
	ID      int64  `db:"id"`
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) error {
	_, err := q.exec(ctx, q.updateNoteStmt, UpdateNote, arg.Content, arg.ID)
	return err
}

const UpdatePipelineState = `-- name: UpdatePipelineState :exec
g');

UPDATE pipeline_state
SET status = ?, started_at = ?, completed_at = ?, error = ?
WHERE item_id = ? AND item_type = ? AND node_id
`

type UpdatePipelineStateParams struct {
	Status      string       `db:"status"`
	StartedAt   sql.NullTime `db:"started_at"`
	CompletedAt sql.NullTime `db:"completed_at"`
	Error       *string      `db:"error"`
	ItemID      int64        `db:"item_id"`
	ItemType    string       `db:"item_type"`
	NodeID      string       `db:"node_id"`
}

func (q *Queries) UpdatePipelineState(ctx context.Context, arg UpdatePipelineStateParams) error {
	_, err := q.exec(ctx, q.updatePipelineStateStmt, UpdatePipelineState,
		arg.Status,
		arg.StartedAt,
		arg.CompletedAt,
		arg.Error,
		arg.ItemID,
		arg.ItemType,
		arg.NodeID,
	)
	return err
}

const UpdatePort = `-- name: UpdatePort :exec
?);

UPDATE ports SET service = ?, banner = ?, source = ?
WHERE ip_id = ? AND port = ? AND protocol
`

type UpdatePortParams struct {
	Service  *string `db:"service"`
	Banner   *string `db:"banner"`
	Source   string  `db:"source"`
	IpID     int64   `db:"ip_id"`
	Port     int64   `db:"port"`
	Protocol string  `db:"protocol"`
}

func (q *Queries) UpdatePort(ctx context.Context, arg UpdatePortParams) error {
	_, err := q.exec(ctx, q.updatePortStmt, UpdatePort,
		arg.Service,
		arg.Banner,
		arg.Source,
		arg.IpID,
		arg.Port,
		arg.Protocol,
	)
	return err
}

const UpdateTechStack = `-- name: UpdateTechStack :exec
?);

UPDATE techstack SET version = ?, category = ?, source = ?
WHERE domain_id = ? AND technology
`

type UpdateTechStackParams struct {
	Version    *string `db:"version"`
	Category   *string `db:"category"`
	Source     string  `db:"source"`
	DomainID   int64   `db:"domain_id"`
	Technology string  `db:"technology"`
}

func (q *Queries) UpdateTechStack(ctx context.Context, arg UpdateTechStackParams) error {
	_, err := q.exec(ctx, q.updateTechStackStmt, UpdateTechStack,
		arg.Version,
		arg.Category,
		arg.Source,
		arg.DomainID,
		arg.Technology,
	)
	return err
}

const UpdateURLDetails = `-- name: UpdateURLDetails :exec
rls;

UPDATE urls
SET status_code = ?, content_type = ?, path = ?, query_string = ?, updated_at = CURRENT_TIMESTAMP
WHERE id
`

type UpdateURLDetailsParams struct {
	StatusCode  *int64  `db:"status_code"`
	ContentType *string `db:"content_type"`
	Path        *string `db:"path"`
	QueryString *string `db:"query_string"`
	ID          int64   `db:"id"`
}

func (q *Queries) UpdateURLDetails(ctx context.Context, arg UpdateURLDetailsParams) error {
	_, err := q.exec(ctx, q.updateURLDetailsStmt, UpdateURLDetails,
		arg.StatusCode,
		arg.ContentType,
		arg.Path,
		arg.QueryString,
		arg.ID,
	)
	return err
}

const UpdateURLFlag = `-- name: UpdateURLFlag :exec
?);

UPDATE url_flags SET source = ? WHERE url_id = ? AND flag_type = ? AND flag_value
`

type UpdateURLFlagParams struct {
	Source    string  `db:"source"`
	UrlID     int64   `db:"url_id"`
	FlagType  string  `db:"flag_type"`
	FlagValue *string `db:"flag_value"`
}

func (q *Queries) UpdateURLFlag(ctx context.Context, arg UpdateURLFlagParams) error {
	_, err := q.exec(ctx, q.updateURLFlagStmt, UpdateURLFlag,
		arg.Source,
		arg.UrlID,
		arg.FlagType,
		arg.FlagValue,
	)
	return err
}
