// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CompleteBatch(ctx context.Context, arg CompleteBatchParams) error
	CompleteProcess(ctx context.Context, arg CompleteProcessParams) error
	CountDomains(ctx context.Context) (int64, error)
	CountFindings(ctx context.Context) (int64, error)
	CountURLs(ctx context.Context) (int64, error)
	DeleteNote(ctx context.Context, id int64) error
	DeleteScopeRuleByPattern(ctx context.Context, pattern string) error
	GetBatchByID(ctx context.Context, id int64) (Batch, error)
	GetDNSRecordsByDomain(ctx context.Context, domainID int64) ([]DnsRecord, error)
	GetDomainByName(ctx context.Context, name string) (Domain, error)
	GetDomains(ctx context.Context, arg GetDomainsParams) ([]Domain, error)
	GetDownloadedFilesByURL(ctx context.Context, urlID int64) ([]DownloadedFile, error)
	GetFindings(ctx context.Context, arg GetFindingsParams) ([]Finding, error)
	GetIPByAddress(ctx context.Context, address string) (Ip, error)
	GetLiveDomains(ctx context.Context, arg GetLiveDomainsParams) ([]Domain, error)
	GetNotes(ctx context.Context) ([]Note, error)
	GetPendingItems(ctx context.Context, arg GetPendingItemsParams) ([]PipelineState, error)
	GetPortsByIP(ctx context.Context, ipID int64) ([]Port, error)
	GetProcessByID(ctx context.Context, id int64) (Process, error)
	GetRunningProcessPIDs(ctx context.Context) ([]*int64, error)
	GetScopeRules(ctx context.Context) ([]ScopeRule, error)
	GetTechStackByDomain(ctx context.Context, domainID int64) ([]Techstack, error)
	GetURLByFullURL(ctx context.Context, fullUrl string) (Url, error)
	GetURLFlagsByURL(ctx context.Context, urlID int64) ([]UrlFlag, error)
	GetURLs(ctx context.Context, arg GetURLsParams) ([]Url, error)
	HasInterruptedSession(ctx context.Context) (int64, error)
	HeartbeatProcess(ctx context.Context, id int64) error
	// ============================================================
	// batches
	// ============================================================
	InsertBatch(ctx context.Context, arg InsertBatchParams) error
	// ============================================================
	// downloaded_files
	// ============================================================
	InsertDownloadedFile(ctx context.Context, arg InsertDownloadedFileParams) error
	// ============================================================
	// findings
	// ============================================================
	InsertFinding(ctx context.Context, arg InsertFindingParams) error
	// ============================================================
	// notes
	// ============================================================
	InsertNote(ctx context.Context, content string) error
	// ============================================================
	// dns_records
	// ============================================================
	InsertOrIgnoreDNSRecord(ctx context.Context, arg InsertOrIgnoreDNSRecordParams) error
	// ============================================================
	// ips
	// ============================================================
	InsertOrIgnoreIP(ctx context.Context, address string) error
	// ============================================================
	// pipeline_state
	// ============================================================
	InsertOrIgnorePipelineState(ctx context.Context, arg InsertOrIgnorePipelineStateParams) error
	// ============================================================
	// ports
	// ============================================================
	InsertOrIgnorePort(ctx context.Context, arg InsertOrIgnorePortParams) error
	// ============================================================
	// techstack
	// ============================================================
	InsertOrIgnoreTechStack(ctx context.Context, arg InsertOrIgnoreTechStackParams) error
	// ============================================================
	// url_flags
	// ============================================================
	InsertOrIgnoreURLFlag(ctx context.Context, arg InsertOrIgnoreURLFlagParams) error
	// ============================================================
	// domains
	// ============================================================
	InsertOrTouchDomain(ctx context.Context, arg InsertOrTouchDomainParams) error
	// ============================================================
	// urls
	// ============================================================
	InsertOrTouchURL(ctx context.Context, arg InsertOrTouchURLParams) error
	// ============================================================
	// processes
	// ============================================================
	InsertProcess(ctx context.Context, arg InsertProcessParams) error
	// Queries for paravizor store.
	// All parameters use ? placeholders — never interpolated — making injection impossible.
	// Note: sqlc's SQLite parser does not support RETURNING or ON CONFLICT...DO UPDATE,
	// so upserts use INSERT OR IGNORE + UPDATE, and inserted IDs are retrieved via last_insert_rowid().
	// ============================================================
	// scope_rules
	// ============================================================
	InsertScopeRule(ctx context.Context, arg InsertScopeRuleParams) error
	ResetProcessingItems(ctx context.Context) (sql.Result, error)
	UpdateDNSRecord(ctx context.Context, arg UpdateDNSRecordParams) error
	UpdateDomainLiveness(ctx context.Context, arg UpdateDomainLivenessParams) error
	UpdateNote(ctx context.Context, arg UpdateNoteParams) error
	UpdatePipelineState(ctx context.Context, arg UpdatePipelineStateParams) error
	UpdatePort(ctx context.Context, arg UpdatePortParams) error
	UpdateTechStack(ctx context.Context, arg UpdateTechStackParams) error
	UpdateURLDetails(ctx context.Context, arg UpdateURLDetailsParams) error
	UpdateURLFlag(ctx context.Context, arg UpdateURLFlagParams) error
}

var _ Querier = (*Queries)(nil)
