# Example config, global or per-project

# ~/.config/paravizor/config.yaml
paravizor:
  # API keys
  api_keys:
    chaos: "your-key-here" # key value store

  theme: "catpuccin-mocha" # looks inside ~/.config/paravizor/themes for the theme definition
  default_pipeline: default # looks inside ~/.config/paravizor/pipelines for the pipeline definition

  max_concurrent_processes: 10
  process_healthcheck_interval: 5

  db:
    busy_timeout: 5000
    mmap_size: 268435456
    cache_size: 8000

  
  log_level: "info"
  ai:
    enabled: false
    provider: ""
    model: ""
    base_url: ""
    api_key: ""
    consent_mode: "always_ask"

